// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketHive.Server.Data;

#nullable disable

namespace TicketHive.Server.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventModelUserModel", b =>
                {
                    b.Property<int>("EventsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("EventsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("EventModelUserModel");
                });

            modelBuilder.Entity("TicketHive.Shared.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFullyBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldTickets")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2023, 12, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Harry Potter Film Concert Series is a unique and immersive experience that combines the magic of film with the enchanting power of live music. \n\nThe series features the beloved Harry Potter films projected on a giant screen while a live symphony orchestra performs the unforgettable score composed by the legendary John Williams and later by Patrick Doyle, Nicholas Hooper, and Alexandre Desplat. Audiences of all ages can relive the adventures of Harry, Ron, and Hermione in a whole new way, as the live music adds a new dimension to the beloved story.\n\nThe Harry Potter Film Concert Series is a must-see for any Harry Potter fan and a testament to the enduring power of the Wizarding World.",
                            EventType = "Concert",
                            Image = "harrypotter",
                            IsFullyBooked = false,
                            Location = "Sweden",
                            MaxCapacity = 500,
                            Name = "Harry Potter In Concert",
                            SoldTickets = 287,
                            TicketPrice = 450m
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 3, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "BronyCon was an annual fan convention held on the East Coast of the United States for fans of My Little Pony: Friendship Is Magic, among them adult and teenage bronies.\n\nEleven events were held, with the final one in August 2019 drawing in 10,215 attendees. Though originally planned to run through 2025 it was announced at the closing ceremonies of the 2018 convention that 2019 would be the final year, tying in with the final season of the show.\n\nBronyCon was previously styled as BroNYCon, as its first three conventions were held in New York City. It dropped the 'NYC' capitalization for its fourth event, which was held in nearby Secaucus, New Jersey. The 2013 event marked the convention's move to Baltimore, Maryland, as well as a shift from twice a year to once a year.",
                            EventType = "Convention",
                            Image = "bronycon",
                            IsFullyBooked = false,
                            Location = "Denmark",
                            MaxCapacity = 400,
                            Name = "BronyCon",
                            SoldTickets = 17,
                            TicketPrice = 950m
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2023, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meet up with the local talent Albin for adventures and fun! In a world with dungeons and dragons explore new territory, clash with dark monsters, spin lore and commit heroic feats while playing the greatest RPG of all time!\n\nIn Dungeons and Dragons your group works together on adventures. A group will have a mixture of different types of characters with different strengths and weaknesses. As a team, you decide how you’re going to approach an encounter to make the most of each character’s skills and abilities and support each other.",
                            EventType = "Games",
                            Image = "dndalbin",
                            IsFullyBooked = true,
                            Location = "Sweden",
                            MaxCapacity = 5,
                            Name = "D&D with Albin",
                            SoldTickets = 5,
                            TicketPrice = 20m
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2023, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Internet Cat Video Festival was a national competition that celebrates cat videos on the internet. Many of these festivals include appearances by special guests and celebricats (such as Grumpy Cat and the creator of Nyan Cat), live music, costume contests, art projects, and booths hosting local animal resource nonprofits. The 2013 Minneapolis show featured a cat sculpture made out of butter.\n\nThe fourth and last Film Festival took place in 2015. Walker Art Center discontinued the event \"to put our resources towards the remodeling of the campus including the Minneapolis Sculpture Garden,” according to spokeswoman Rachel Joyce. All of the festival memorabilia was given to the Minnesota Historical Society.",
                            EventType = "Festival",
                            Image = "internetcatfest",
                            IsFullyBooked = false,
                            Location = "Poland",
                            MaxCapacity = 700,
                            Name = "Internet Cat Video Festival",
                            SoldTickets = 159,
                            TicketPrice = 300m
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2023, 3, 17, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flottkalaset (Raft Festival) is an annual music festival and cultural event held in Tjautjas in the Gällivare Municipality region in northern Sweden. The event was envisioned and organized by Riksspelman Daniel Wikslund, a noted Swedish folk musician.\n\nThe two-day festival takes place in August on an island in the middle of a mountain lake, accessible via rafts or by walking across a raft bridge.",
                            EventType = "Festival",
                            Image = "flottkalaset",
                            IsFullyBooked = false,
                            Location = "Sweden",
                            MaxCapacity = 400,
                            Name = "Flottkalaset",
                            SoldTickets = 89,
                            TicketPrice = 150m
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2023, 8, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "World’s biggest food fight. Thousands of people make the pilgrimage to the ancient town of Buñol at the end of August every year to party and pelt each other with tomatoes. Trucks carrying 40 tonnes of tomatoes rock up in the centre of town. Get ready for the undisputed king of food fight festivals.",
                            EventType = "Festival",
                            Image = "latomatina",
                            IsFullyBooked = false,
                            Location = "Spain",
                            MaxCapacity = 3000,
                            Name = "La Tomatina",
                            SoldTickets = 2439,
                            TicketPrice = 200m
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2023, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Guca Trumpet Festival is a celebration of trumpet culture in Serbian folk music, an instrument that has deep historical and political ties to the country. The event has been around since 1961, and today it is considered by many to be among the world’s best folk and music festivals.\n\nUpon first glance, the festival may not seem that much different from other music festivals. There are tented pop-up bars and stalls selling food, but it’s injected with a whole lot of authentic Serbian elements: whole roasted animals are on display, inviting carnivores to eat to their heart’s content. Get drunk on the music and rakija as you revel in the folk dances where performers are decked out in bright costumes entertaining an energetic audience.",
                            EventType = "Festival",
                            Image = "gucatrumpet",
                            IsFullyBooked = false,
                            Location = "Serbia",
                            MaxCapacity = 2500,
                            Name = "Guca Trumpet Festival",
                            SoldTickets = 570,
                            TicketPrice = 350m
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2023, 7, 4, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Nathan's Famous International Hot Dog Eating Contest is an annual American hot dog competitive eating competition. It is held each year on July 4th at Nathan's Famous Corporation's original, and best-known restaurant at the corner of Surf and Stillwell Avenues in Coney Island, a neighborhood of Brooklyn, New York City.\n\nThe contest has gained public attention in recent years due to the stardom of Takeru \"The Tsunami\" Kobayashi and Joey \"Jaws\" Chestnut. The defending men's champion is Chestnut, who ate 63 hot dogs in the 2022 contest. The defending women's champion is Miki Sudo, who ate 40 hot dogs in 2022.",
                            EventType = "Competition",
                            Image = "nathanshotdog",
                            IsFullyBooked = false,
                            Location = "USA",
                            MaxCapacity = 1500,
                            Name = "Nathan's Hot Dog Eating Contest",
                            SoldTickets = 264,
                            TicketPrice = 50m
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2023, 3, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Everybody’s favorite Drag Queens are back on Friday March 24 for a command performance in our gorgeous winery ballroom.\n\nIt’ll be a night of Burlesque, Bites and Booze with this super fun and unforgettable 21+ Drag Show Cocktail Party. Admission is $65/pp. This includes the show and free Hors D’oeuvres during the 2 hour cocktail hour before. (Cash bar will be open all evening).",
                            EventType = "Party",
                            Image = "dragqueen",
                            IsFullyBooked = false,
                            Location = "USA",
                            MaxCapacity = 75,
                            Name = "Drag Queen Burlesque",
                            SoldTickets = 69,
                            TicketPrice = 650m
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2023, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DreamHack is an ESL Gaming brand specializing in esports tournaments and other gaming conventions. It is recognized by the Guinness Book of Records and Twin Galaxies as being the world's largest LAN party and computer festival with the world's fastest Internet connection. It usually holds its events in Western Europe and North America.\n\nDreamHack's events include local area network gatherings with live concerts and competitions in digital art and esports. The first event was held in Malung, Sweden. The company has held several gaming events throughout Europe, in Stockholm, Jönköping, Tours, Bucharest, Cluj, Valencia, Seville, London, and Leipzig. In May 2016, it held its first North American event in Austin, Texas. In August 2016, it held its first Canada event in Montreal, Quebec. Winter events consistently have about 10% more visitors than summer events.",
                            EventType = "Games",
                            Image = "dreamhack",
                            IsFullyBooked = false,
                            Location = "Sweden",
                            MaxCapacity = 750,
                            Name = "DreamHack",
                            SoldTickets = 630,
                            TicketPrice = 890m
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2023, 7, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Joddla Med Siv is a Swedish comedy-folk-rock band from Hässleholm in Skåne, south Sweden. They formed in February 1990, and today the band has 8 records to be proud about. They have sold about 35 000 records just in the region of Skåne.",
                            EventType = "Concert",
                            Image = "joddlamedsiv",
                            IsFullyBooked = false,
                            Location = "Sweden",
                            MaxCapacity = 30,
                            Name = "Joddla Med Siv",
                            SoldTickets = 11,
                            TicketPrice = 29m
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2023, 2, 28, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trazan & Banarne was a Swedish children's television series which was broadcast from 1976 to 1982 on Sveriges Television. For its first season from 1976 to 1977, it was part of the Jullovsmorgon series. The title characters were played by Lasse Åberg (Trazan Apansson) and Klasse Möllberg (Banarne), and they recorded many songs together with the band Electric Banana Band.",
                            EventType = "Concert",
                            Image = "trazanbanarne",
                            IsFullyBooked = false,
                            Location = "Sweden",
                            MaxCapacity = 50,
                            Name = "Trazan & Banarne",
                            SoldTickets = 48,
                            TicketPrice = 3799m
                        });
                });

            modelBuilder.Entity("TicketHive.Shared.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "user"
                        },
                        new
                        {
                            Id = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EventModelUserModel", b =>
                {
                    b.HasOne("TicketHive.Shared.EventModel", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketHive.Shared.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
